<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MusaKalim" failures="3" tests="5" name="Test" time="0.066" errors="0" timestamp="13 May 2023 23:24:35 GMT">
  <testcase classname="smarttech.nyc.testNGChallenges.FailedTestCases" name="getTestFour" time="0.021"/>
  <testcase classname="smarttech.nyc.testNGChallenges.FailedTestCases" name="getTestTwo" time="0.021"/>
  <testcase classname="smarttech.nyc.testNGChallenges.FailedTestCases" name="getTestThree" time="0.021">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.nyc.testNGChallenges.FailedTestCases.getTestThree(FailedTestCases.java:20)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- getTestThree -->
  <testcase classname="smarttech.nyc.testNGChallenges.FailedTestCases" name="getTestFive" time="0.023">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.nyc.testNGChallenges.FailedTestCases.getTestFive(FailedTestCases.java:30)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- getTestFive -->
  <testcase classname="smarttech.nyc.testNGChallenges.FailedTestCases" name="getTestOne" time="0.023">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.nyc.testNGChallenges.FailedTestCases.getTestOne(FailedTestCases.java:10)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- getTestOne -->
</testsuite> <!-- Test -->
